package Models;
// Generated 10-jul-2017 16:17:01 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Cuenta generated by hbm2java
 */
public class Cuenta  implements java.io.Serializable {


     private Integer idCuenta;
     private String usuario;
     private byte[] password;
     private Date ultimoAcceso;
     private int empresaIdEmpresa;
     private String nombrePersona;

    public Cuenta() {
    }

	
    public Cuenta(String usuario, byte[] password, int empresaIdEmpresa) {
        this.usuario = usuario;
        this.password = password;
        this.empresaIdEmpresa = empresaIdEmpresa;
    }
    public Cuenta(String usuario, byte[] password, Date ultimoAcceso, int empresaIdEmpresa, String nombrePersona) {
       this.usuario = usuario;
       this.password = password;
       this.ultimoAcceso = ultimoAcceso;
       this.empresaIdEmpresa = empresaIdEmpresa;
       this.nombrePersona = nombrePersona;
    }
   
    public Integer getIdCuenta() {
        return this.idCuenta;
    }
    
    public void setIdCuenta(Integer idCuenta) {
        this.idCuenta = idCuenta;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public byte[] getPassword() {
        return this.password;
    }
    
    public void setPassword(byte[] password) {
        this.password = password;
    }
    public Date getUltimoAcceso() {
        return this.ultimoAcceso;
    }
    
    public void setUltimoAcceso(Date ultimoAcceso) {
        this.ultimoAcceso = ultimoAcceso;
    }
    public int getEmpresaIdEmpresa() {
        return this.empresaIdEmpresa;
    }
    
    public void setEmpresaIdEmpresa(int empresaIdEmpresa) {
        this.empresaIdEmpresa = empresaIdEmpresa;
    }
    public String getNombrePersona() {
        return this.nombrePersona;
    }
    
    public void setNombrePersona(String nombrePersona) {
        this.nombrePersona = nombrePersona;
    }




}


