package Models;
// Generated 10-jul-2017 16:17:01 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Empresa generated by hbm2java
 */
public class Empresa  implements java.io.Serializable {


     private Integer idEmpresa;
     private String rucEmpresa;
     private String nombreComercial;
     private String direccionFiscal;
     private String tipoEmpresa;
     private Date fechaCreacion;
     private String estado;
     private String email;
     private String logo;
     private String ubigeo;
     private String telefono;

    public Empresa() {
    }

	
    public Empresa(String rucEmpresa, String nombreComercial, String direccionFiscal, String tipoEmpresa, Date fechaCreacion, String estado, String ubigeo, String telefono) {
        this.rucEmpresa = rucEmpresa;
        this.nombreComercial = nombreComercial;
        this.direccionFiscal = direccionFiscal;
        this.tipoEmpresa = tipoEmpresa;
        this.fechaCreacion = fechaCreacion;
        this.estado = estado;
        this.ubigeo = ubigeo;
        this.telefono = telefono;
    }
    public Empresa(String rucEmpresa, String nombreComercial, String direccionFiscal, String tipoEmpresa, Date fechaCreacion, String estado, String logo, String ubigeo, String telefono) {
       this.rucEmpresa = rucEmpresa;
       this.nombreComercial = nombreComercial;
       this.direccionFiscal = direccionFiscal;
       this.tipoEmpresa = tipoEmpresa;
       this.fechaCreacion = fechaCreacion;
       this.estado = estado;
       this.logo = logo;
       this.ubigeo = ubigeo;
       this.telefono = telefono;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }
    
    public Integer getIdEmpresa() {
        return this.idEmpresa;
    }
    
    public void setIdEmpresa(Integer idEmpresa) {
        this.idEmpresa = idEmpresa;
    }
    public String getRucEmpresa() {
        return this.rucEmpresa;
    }
    
    public void setRucEmpresa(String rucEmpresa) {
        this.rucEmpresa = rucEmpresa;
    }
    public String getNombreComercial() {
        return this.nombreComercial;
    }
    
    public void setNombreComercial(String nombreComercial) {
        this.nombreComercial = nombreComercial;
    }
    public String getDireccionFiscal() {
        return this.direccionFiscal;
    }
    
    public void setDireccionFiscal(String direccionFiscal) {
        this.direccionFiscal = direccionFiscal;
    }
    public String getTipoEmpresa() {
        return this.tipoEmpresa;
    }
    
    public void setTipoEmpresa(String tipoEmpresa) {
        this.tipoEmpresa = tipoEmpresa;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public String getLogo() {
        return this.logo;
    }
    
    public void setLogo(String logo) {
        this.logo = logo;
    }
    public String getUbigeo() {
        return this.ubigeo;
    }
    
    public void setUbigeo(String ubigeo) {
        this.ubigeo = ubigeo;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }

    public static String getProvincia(String ubigeo){
        String[] datos=ubigeo.split("-");
        return datos[1];
    }
    public static String getDistrito(String ubigeo){
        String[] datos=ubigeo.split("-");
        return datos[0];
    }
    public static String getDepartamento(String ubigeo){
        String[] datos=ubigeo.split("-");
        return datos[2];
    }


}


