package Models;
// Generated 10-jul-2017 16:17:01 by Hibernate Tools 4.3.1



/**
 * EmpresaHasCliente generated by hbm2java
 */
public class EmpresaHasCliente  implements java.io.Serializable {


     private EmpresaHasClienteId id;

    public EmpresaHasCliente() {
    }

    public EmpresaHasCliente(EmpresaHasClienteId id) {
       this.id = id;
    }
   
    public EmpresaHasClienteId getId() {
        return this.id;
    }
    
    public void setId(EmpresaHasClienteId id) {
        this.id = id;
    }




}


