package Models;
// Generated 10-jul-2017 16:17:01 by Hibernate Tools 4.3.1



/**
 * PermisoHasCuenta generated by hbm2java
 */
public class PermisoHasCuenta  implements java.io.Serializable {


     private PermisoHasCuentaId id;

    public PermisoHasCuenta() {
    }

    public PermisoHasCuenta(PermisoHasCuentaId id) {
       this.id = id;
    }
   
    public PermisoHasCuentaId getId() {
        return this.id;
    }
    
    public void setId(PermisoHasCuentaId id) {
        this.id = id;
    }




}


