package Models;
// Generated 10-jul-2017 16:17:01 by Hibernate Tools 4.3.1



/**
 * ProductoHasComprobantePago generated by hbm2java
 */
public class ProductoHasComprobantePago  implements java.io.Serializable {


     private ProductoHasComprobantePagoId id;
     private float cantidad;
     private Float descuento;

    public ProductoHasComprobantePago() {
    }

	
    public ProductoHasComprobantePago(ProductoHasComprobantePagoId id, float cantidad) {
        this.id = id;
        this.cantidad = cantidad;
    }
    public ProductoHasComprobantePago(ProductoHasComprobantePagoId id, float cantidad, Float descuento) {
       this.id = id;
       this.cantidad = cantidad;
       this.descuento = descuento;
    }
   
    public ProductoHasComprobantePagoId getId() {
        return this.id;
    }
    
    public void setId(ProductoHasComprobantePagoId id) {
        this.id = id;
    }
    public float getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(float cantidad) {
        this.cantidad = cantidad;
    }
    public Float getDescuento() {
        return this.descuento;
    }
    
    public void setDescuento(Float descuento) {
        this.descuento = descuento;
    }




}


