package Models;
// Generated 10-jul-2017 16:17:01 by Hibernate Tools 4.3.1



/**
 * TipoComprobante generated by hbm2java
 */
public class TipoComprobante  implements java.io.Serializable {


     private String idTipoComprobante;
     private String nombreComprobante;
     private String numTipoComprobante;
     private String abreviatura;
     private int indAfectoRetencion;

    public TipoComprobante() {
    }

	
    public TipoComprobante(String idTipoComprobante, String nombreComprobante, int indAfectoRetencion) {
        this.idTipoComprobante = idTipoComprobante;
        this.nombreComprobante = nombreComprobante;
        this.indAfectoRetencion = indAfectoRetencion;
    }
    public TipoComprobante(String idTipoComprobante, String nombreComprobante, String abreviatura, int indAfectoRetencion) {
       this.idTipoComprobante = idTipoComprobante;
       this.nombreComprobante = nombreComprobante;
       this.abreviatura = abreviatura;
       this.indAfectoRetencion = indAfectoRetencion;
    }

    public String getNumTipoComprobante() {
        return numTipoComprobante;
    }

    public void setNumTipoComprobante(String numTipoComprobante) {
        this.numTipoComprobante = numTipoComprobante;
    }
    
    public String getIdTipoComprobante() {
        return this.idTipoComprobante;
    }
    
    public void setIdTipoComprobante(String idTipoComprobante) {
        this.idTipoComprobante = idTipoComprobante;
    }
    public String getNombreComprobante() {
        return this.nombreComprobante;
    }
    
    public void setNombreComprobante(String nombreComprobante) {
        this.nombreComprobante = nombreComprobante;
    }
    public String getAbreviatura() {
        return this.abreviatura;
    }
    
    public void setAbreviatura(String abreviatura) {
        this.abreviatura = abreviatura;
    }
    public int getIndAfectoRetencion() {
        return this.indAfectoRetencion;
    }
    
    public void setIndAfectoRetencion(int indAfectoRetencion) {
        this.indAfectoRetencion = indAfectoRetencion;
    }




}


