package Models;
// Generated 10-jul-2017 16:17:01 by Hibernate Tools 4.3.1



/**
 * Ubdistrito generated by hbm2java
 */
public class Ubdistrito  implements java.io.Serializable {


     private int idDist;
     private Ubprovincia ubprovincia;
     private String distrito;

    public Ubdistrito() {
    }

    public Ubdistrito(int idDist, Ubprovincia ubprovincia, String distrito) {
       this.idDist = idDist;
       this.ubprovincia = ubprovincia;
       this.distrito = distrito;
    }
   
    public int getIdDist() {
        return this.idDist;
    }
    
    public void setIdDist(int idDist) {
        this.idDist = idDist;
    }
    public Ubprovincia getUbprovincia() {
        return this.ubprovincia;
    }
    
    public void setUbprovincia(Ubprovincia ubprovincia) {
        this.ubprovincia = ubprovincia;
    }
    public String getDistrito() {
        return this.distrito;
    }
    
    public void setDistrito(String distrito) {
        this.distrito = distrito;
    }




}


