/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import Controllers.ConnectionDB;
import Controllers.Validador;
import Models.CorreoEmpresa;
import Models.Empresa;
import com.apple.eawt.Application;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


/**
 *
 * @author javierfuenteshuertas
 */
public class ConfigurarCorreoView extends javax.swing.JFrame {

    /**
     * Creates new form ConfigurarCorreoView
     */
    private ConnectionDB conexion;
    private Connection conn;
    private Empresa empresa;
    private CorreoEmpresa correo;
    private String passwordEmail;
    public ConfigurarCorreoView(Empresa empresa) {
        initComponents();
        conexion=new ConnectionDB();
        conn=conexion.connect(conn);
        this.empresa=empresa;
        eventosTeclado();
        inciarDatosCorreo();
        this.getRootPane().setDefaultButton(jbAceptar);
        String sSistemaOperativo = System.getProperty("os.name");
        if(sSistemaOperativo.equals("Mac OS X")){
            Application application = Application.getApplication();
            Image image = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Images/logoKipu.png"));
            application.setDockIconImage(image);
        }
        else{
            Image icon = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Images/logoKipu.png"));
            this.setIconImage(icon);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtPassword = new javax.swing.JPasswordField();
        jtEmail = new javax.swing.JTextField();
        jtHost = new javax.swing.JTextField();
        jtPort = new javax.swing.JTextField();
        jcbStartTtls = new javax.swing.JCheckBox();
        jbCancelar = new javax.swing.JButton();
        jbAceptar = new javax.swing.JButton();

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));

        jLabel1.setText("Email:");

        jLabel2.setText("Password:");

        jLabel3.setText("Host:");

        jLabel4.setText("Port:");

        jcbStartTtls.setText("StarTTLS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtPassword)
                    .addComponent(jtEmail, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jtHost)
                    .addComponent(jtPort)
                    .addComponent(jcbStartTtls, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtHost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jcbStartTtls)
                .addContainerGap())
        );

        jbCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/error.png"))); // NOI18N
        jbCancelar.setText("Cancelar");
        jbCancelar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbCancelar.setSelected(true);
        jbCancelar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarActionPerformed(evt);
            }
        });

        jbAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/success.png"))); // NOI18N
        jbAceptar.setText("Aceptar");
        jbAceptar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbAceptar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbAceptar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jbCancelarActionPerformed

    private void jbAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAceptarActionPerformed
        if(Validador.isEmail(jtEmail.getText())){
            modificarCuenta();
        }
        else JOptionPane.showMessageDialog(this, "Email no válido","El email ingresado no cumple con la sintaxis",JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_jbAceptarActionPerformed

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbAceptar;
    private javax.swing.JButton jbCancelar;
    private javax.swing.JCheckBox jcbStartTtls;
    private javax.swing.JTextField jtEmail;
    private javax.swing.JTextField jtHost;
    private javax.swing.JPasswordField jtPassword;
    private javax.swing.JTextField jtPort;
    // End of variables declaration//GEN-END:variables

    private void eventosTeclado() {
       getRootPane().getInputMap(javax.swing.JComponent.WHEN_IN_FOCUSED_WINDOW).put(
            javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0), "Cancel");
        
        getRootPane().getActionMap().put("Cancel", new javax.swing.AbstractAction(){
            @Override
            public void actionPerformed(java.awt.event.ActionEvent e)
            {
               setVisible(false);
            }
        });
        getRootPane().getInputMap(javax.swing.JComponent.WHEN_IN_FOCUSED_WINDOW).put(
            javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ENTER, 0), "Add");
        
        getRootPane().getActionMap().put("Add", new javax.swing.AbstractAction(){
            @Override
            public void actionPerformed(java.awt.event.ActionEvent e)
            {
               modificarCuenta();
            }
        });
    }
    private void modificarCuenta(){
        PreparedStatement stmt;
        try {
            stmt = conn.prepareStatement("update correoempresa set email=? ,passwordEmail=?, host=?,port=?,starttls=? where Empresa_idEmpresa=?"); 
            stmt.setString(1, jtEmail.getText());
            String tempPass=String.valueOf(jtPassword.getPassword());
            stmt.setString(2, tempPass);
            stmt.setString(3, jtHost.getText());
            stmt.setString(4, jtPort.getText());
            stmt.setString(5, String.valueOf(jcbStartTtls.isSelected()));
            stmt.setInt(6, empresa.getIdEmpresa());
            stmt.executeUpdate();
            JOptionPane.showMessageDialog(this, "Se modificaron los cambios");
            this.setVisible(false);
        } catch (SQLException ex) {
            Logger.getLogger(ConfigurarCorreoView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void inciarDatosCorreo() {
        PreparedStatement stmt;
        try {
            stmt = conn.prepareStatement("select *,AES_DECRYPT(passwordEmail, 'LCNDUWF172006000')AS pass from correoempresa where Empresa_idEmpresa=?");
            stmt.setInt(1, empresa.getIdEmpresa());
            ResultSet rs=stmt.executeQuery();
            correo=new CorreoEmpresa();
            if(rs.next()){
                correo.setEmail(rs.getString("email"));
                correo.setStarttls(rs.getString("starttls"));
                correo.setHost(rs.getString("host"));
                correo.setPort(rs.getString("port"));
                passwordEmail=rs.getString("pass");
            }
            if(correo.getEmail().length()>0){
                jtEmail.setText(correo.getEmail());
                jtHost.setText(correo.getHost());
                jtPort.setText(correo.getPort());
                jcbStartTtls.setSelected(Boolean.valueOf(correo.getStarttls()));
                jtPassword.setText(passwordEmail);
            }
        } catch (SQLException ex) {
            Logger.getLogger(ConfigurarCorreoView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
