/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;


import Controllers.ConnectionDB;
import Controllers.PanelTab;
import Models.Cuenta;
import Models.Empresa;
import com.apple.eawt.Application;
import java.awt.Event;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.image.BufferedImage;
import java.io.BufferedReader;
import java.io.File;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.net.MalformedURLException;
import java.net.URL;
import java.net.URLConnection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.ImageIcon;
import javax.swing.JComponent;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.KeyStroke;
import javax.swing.Timer;
import sun.awt.image.ToolkitImage;





/**
 *
 * @author javierfuenteshuertas
 */
public class MainView extends javax.swing.JFrame {

    /**
     * Creates new form MainView
     */
    private final Empresa empresa;
    private int idCuenta;
    private static Float COMPRA=0.0f;
    private static Float VENTA=0.0f;
    private ConnectionDB conexion;
    private Connection conn;
    private Cuenta cuenta;
    private Timer timer= null;
    private int countTimer=0;
    private final String[] tipoNotaCredito={"Anulación de la operación","Anulación por error en el RUC","Corrección por error en la descripción",
    "Descuento global","Descuento por Item","Devolución total","Devolución parcial","Bonificación","Disminución en el valor"};
    private final String[] tipoNotaDébito={"Intereses por mora","Aumento en el valor","Penalidades"};
    public MainView(Empresa empresa,int idUsuario){
        initComponents();
        this.empresa=empresa;
        this.idCuenta=idUsuario;
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        conexion=new ConnectionDB();
        conn=conexion.connect(conn);
        datosEmpresa();
        agregarTipoCambio();
        eventosTeclado();
        iniciarTabInicio();
        String sSistemaOperativo = System.getProperty("os.name");
        if(sSistemaOperativo.equals("Mac OS X")){
            Application application = Application.getApplication();
            Image image = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Images/logoKipu.png"));
            application.setDockIconImage(image);
        }
        else{
            Image icon = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Images/logoKipu.png"));
            this.setIconImage(icon);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpInformacion = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jlNombreEmpresa = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jlUsuario = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jlCompraSunat = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jlVentaSunat = new javax.swing.JLabel();
        jpComprobantes = new javax.swing.JPanel();
        jbFactura = new javax.swing.JButton();
        jbBoleta = new javax.swing.JButton();
        jbNotaCredito = new javax.swing.JButton();
        jbNotaDebito = new javax.swing.JButton();
        jtpTrabajo = new javax.swing.JTabbedPane();
        jpInicio = new javax.swing.JPanel();
        jlLogo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmRegistro = new javax.swing.JMenu();
        jmiFactura = new javax.swing.JMenuItem();
        jmiBoleta = new javax.swing.JMenuItem();
        jmiNotaCredito = new javax.swing.JMenuItem();
        jmiNotaDebito = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));
        setSize(new java.awt.Dimension(800, 600));

        jpInformacion.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/flats-2.png"))); // NOI18N

        jlNombreEmpresa.setFont(new java.awt.Font("AppleGothic", 0, 14)); // NOI18N
        jlNombreEmpresa.setText("Nombre de Empresa");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlNombreEmpresa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jlNombreEmpresa))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/network.png"))); // NOI18N

        jlUsuario.setFont(new java.awt.Font("AppleGothic", 0, 14)); // NOI18N
        jlUsuario.setText("Usuario");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlUsuario)
                .addContainerGap(108, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlUsuario)
                    .addComponent(jLabel8))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel6.setMaximumSize(new java.awt.Dimension(280, 34));
        jPanel6.setPreferredSize(new java.awt.Dimension(280, 34));
        jPanel6.setSize(new java.awt.Dimension(280, 34));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/sunat_logo.png"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("AppleGothic", 0, 14)); // NOI18N
        jLabel4.setText("Compra:");

        jlCompraSunat.setFont(new java.awt.Font("AppleGothic", 0, 14)); // NOI18N
        jlCompraSunat.setText("0.000");

        jLabel5.setFont(new java.awt.Font("AppleGothic", 0, 14)); // NOI18N
        jLabel5.setText("  Venta :");

        jlVentaSunat.setFont(new java.awt.Font("AppleGothic", 0, 14)); // NOI18N
        jlVentaSunat.setText("0.000");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlCompraSunat)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlVentaSunat)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jlCompraSunat)
                            .addComponent(jLabel5)
                            .addComponent(jlVentaSunat)))
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jpInformacionLayout = new javax.swing.GroupLayout(jpInformacion);
        jpInformacion.setLayout(jpInformacionLayout);
        jpInformacionLayout.setHorizontalGroup(
            jpInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpInformacionLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jpInformacionLayout.setVerticalGroup(
            jpInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jpComprobantes.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, new java.awt.Color(153, 153, 153)));
        jpComprobantes.setMaximumSize(new java.awt.Dimension(100, 32767));

        jbFactura.setFont(new java.awt.Font("AppleGothic", 0, 14)); // NOI18N
        jbFactura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/factura.png"))); // NOI18N
        jbFactura.setText("<html>Factura<br><center>[F1]</center></html>");
        jbFactura.setFocusPainted(false);
        jbFactura.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbFactura.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbFacturaActionPerformed(evt);
            }
        });

        jbBoleta.setFont(new java.awt.Font("AppleGothic", 0, 14)); // NOI18N
        jbBoleta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/boleta.png"))); // NOI18N
        jbBoleta.setText("<html>Boleta<br><center>[F2]</center></html>");
        jbBoleta.setFocusable(false);
        jbBoleta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbBoleta.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbBoleta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBoletaActionPerformed(evt);
            }
        });

        jbNotaCredito.setFont(new java.awt.Font("AppleGothic", 0, 14)); // NOI18N
        jbNotaCredito.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/noteCredito.png"))); // NOI18N
        jbNotaCredito.setText("<html>Nota Crédito<br><center>[F3]</center></html>");
        jbNotaCredito.setFocusable(false);
        jbNotaCredito.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbNotaCredito.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbNotaCredito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNotaCreditoActionPerformed(evt);
            }
        });

        jbNotaDebito.setFont(new java.awt.Font("AppleGothic", 0, 14)); // NOI18N
        jbNotaDebito.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/noteDebito.png"))); // NOI18N
        jbNotaDebito.setText("<html>Nota Débito<br><center>[F4]</center></html>");
        jbNotaDebito.setFocusable(false);
        jbNotaDebito.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbNotaDebito.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbNotaDebito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNotaDebitoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpComprobantesLayout = new javax.swing.GroupLayout(jpComprobantes);
        jpComprobantes.setLayout(jpComprobantesLayout);
        jpComprobantesLayout.setHorizontalGroup(
            jpComprobantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpComprobantesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpComprobantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbFactura)
                    .addComponent(jbBoleta)
                    .addComponent(jbNotaCredito)
                    .addComponent(jbNotaDebito))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpComprobantesLayout.setVerticalGroup(
            jpComprobantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpComprobantesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbFactura)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbBoleta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbNotaCredito)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbNotaDebito)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpInicio.setBackground(new java.awt.Color(255, 255, 255));
        jpInicio.setLayout(new java.awt.GridBagLayout());
        jpInicio.add(jlLogo, new java.awt.GridBagConstraints());

        jtpTrabajo.addTab("Inicio", null, jpInicio, "");
        PanelTab btc=new PanelTab(jtpTrabajo,1);
        jtpTrabajo.setTabComponentAt(0, btc);

        jmRegistro.setText("Comprobantes");

        jmiFactura.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        jmiFactura.setText("Factura");
        jmiFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiFacturaActionPerformed(evt);
            }
        });
        jmRegistro.add(jmiFactura);

        jmiBoleta.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        jmiBoleta.setText("Boleta");
        jmiBoleta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiBoletaActionPerformed(evt);
            }
        });
        jmRegistro.add(jmiBoleta);

        jmiNotaCredito.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, 0));
        jmiNotaCredito.setText("Nota Crédito");
        jmiNotaCredito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiNotaCreditoActionPerformed(evt);
            }
        });
        jmRegistro.add(jmiNotaCredito);

        jmiNotaDebito.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, 0));
        jmiNotaDebito.setText("Nota Débito");
        jmRegistro.add(jmiNotaDebito);

        jMenuBar1.add(jmRegistro);
        jmRegistro.setVisible(false);

        jMenu2.setText("Reportes");

        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/clerk.png"))); // NOI18N
        jMenuItem5.setText("Por cliente");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/timeline.png"))); // NOI18N
        jMenuItem6.setText("Por periodo");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem6);

        jMenuBar1.add(jMenu2);

        jMenu5.setText("Seguridad");

        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/user.png"))); // NOI18N
        jMenuItem3.setText("Crear Usuario");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem3);

        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/key.png"))); // NOI18N
        jMenuItem4.setText("Modificar contraseña");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem4);

        jMenuBar1.add(jMenu5);

        jMenu4.setText("Configuraciones");

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/note.png"))); // NOI18N
        jMenuItem2.setText("Tipo cambio");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem2);

        jMenuItem7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/mail.png"))); // NOI18N
        jMenuItem7.setText("Cuenta correo");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem7);

        jMenuBar1.add(jMenu4);

        jMenu3.setText("Ayuda");

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/customer-service.png"))); // NOI18N
        jMenuItem1.setText("Acerca de");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpInformacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpComprobantes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtpTrabajo)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpComprobantes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtpTrabajo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpInformacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jmiFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiFacturaActionPerformed
        nuevaFactura();
    }//GEN-LAST:event_jmiFacturaActionPerformed

    private void jbFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbFacturaActionPerformed
        nuevaFactura();
    }//GEN-LAST:event_jbFacturaActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        modificarTipoCambio();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        Usuario user=new Usuario(empresa);
        user.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jbBoletaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBoletaActionPerformed
        nuevaBoleta();
    }//GEN-LAST:event_jbBoletaActionPerformed

    private void jmiBoletaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiBoletaActionPerformed
        nuevaBoleta();
    }//GEN-LAST:event_jmiBoletaActionPerformed

    private void jbNotaCreditoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNotaCreditoActionPerformed
        nuevaNotaCredito();
    }//GEN-LAST:event_jbNotaCreditoActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        ViewReporteCliente vrc=new ViewReporteCliente(empresa);
        vrc.setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        CambiarContraseniaView ccv=new CambiarContraseniaView(empresa.getIdEmpresa(), idCuenta);
        ccv.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        ConfigurarCorreoView ccv=new ConfigurarCorreoView(empresa);
        ccv.setVisible(true);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        ViewVentasPeriodo vvp=new ViewVentasPeriodo(empresa);
        vvp.setVisible(true);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jmiNotaCreditoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiNotaCreditoActionPerformed
        nuevaNotaCredito();
    }//GEN-LAST:event_jmiNotaCreditoActionPerformed

    private void jbNotaDebitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNotaDebitoActionPerformed
        nuevaNotaDebito();
    }//GEN-LAST:event_jbNotaDebitoActionPerformed

    /**
     * @param args the command line arguments
     */
    /*
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        /*try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainView().setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JButton jbBoleta;
    private javax.swing.JButton jbFactura;
    private javax.swing.JButton jbNotaCredito;
    private javax.swing.JButton jbNotaDebito;
    private javax.swing.JLabel jlCompraSunat;
    private javax.swing.JLabel jlLogo;
    private javax.swing.JLabel jlNombreEmpresa;
    private javax.swing.JLabel jlUsuario;
    private javax.swing.JLabel jlVentaSunat;
    private javax.swing.JMenu jmRegistro;
    private javax.swing.JMenuItem jmiBoleta;
    private javax.swing.JMenuItem jmiFactura;
    private javax.swing.JMenuItem jmiNotaCredito;
    private javax.swing.JMenuItem jmiNotaDebito;
    private javax.swing.JPanel jpComprobantes;
    private javax.swing.JPanel jpInformacion;
    private javax.swing.JPanel jpInicio;
    private javax.swing.JTabbedPane jtpTrabajo;
    // End of variables declaration//GEN-END:variables

    private boolean tipoCambioSunat() {
        try {
            String tempMes;
            Calendar now =Calendar.getInstance();   
            if((now.get(Calendar.MONTH)+1)<10){
                tempMes="0"+String.valueOf((now.get(Calendar.MONTH)+1));
            }
            else{
                tempMes=String.valueOf((now.get(Calendar.MONTH)+1));
            }
            URL url = new  URL("http://www.sunat.gob.pe/cl-at-ittipcam/tcS01Alias?mes="+tempMes+"&anho="+String.valueOf(now.get(Calendar.YEAR)));
            URLConnection con;
            Boolean band=false;
            ArrayList<String> listTipoCambio=new ArrayList<String>();
            try {
                con = url.openConnection(); 
                con.setConnectTimeout(5000);
                con.setReadTimeout(5000);
                InputStream is =con.getInputStream();
                BufferedReader br = new BufferedReader(new InputStreamReader(is));
                String line = null;
                // read each line and write to System.out
                while ((line = br.readLine()) != null) {
                    if(line.equals("        <td width='4%' align='center' class=\"H3\">"))band=true;
                    if(band){
                        if(line.equals(" </table>"))break;
                        if(!line.equals("        <td width='8%' align='center' class=\"tne10\">") && !line.equals("        </td>") && !line.equals("          </tr>") && !line.equals("          <tr>") && !line.equals("        <td width='4%' align='center' class=\"H3\">" ) && !line.contains("<strong>") && !line.equals("          ") && !line.equals("        ") && !line.equals("      			")){
                            String temp=line.replaceAll("\\s","");
                            //System.out.println(temp);
                            listTipoCambio.add(temp);
                        }    
                    }
                }
                //System.out.println(data);
                clearString(listTipoCambio);
                return true;
            } catch (IOException ex) {
                Logger.getLogger(MainView.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, "No se establece conexión con SUNAT, se ingresará el tipo de cambio manualmente");
                modificarTipoCambio();
            }
            } catch (MalformedURLException ex) {
                Logger.getLogger(MainView.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, "No se establece conexión con SUNAT, se ingresará el tipo de cambio manualmente");
            }
        return false;
    }

    private void clearString(ArrayList<String> data) {
        COMPRA=Float.parseFloat(data.get(data.size()-5));
        VENTA=Float.parseFloat(data.get(data.size()-4));
        asginarTipoCambio();
    }

    private void nuevaFactura() {
       Comprobante comprobantePago=new Comprobante(this.jtpTrabajo,this.empresa,"F", COMPRA, VENTA,idCuenta);
       jtpTrabajo.addTab("Nueva Factura",comprobantePago);
       jtpTrabajo.setSelectedIndex(jtpTrabajo.getTabCount()-1);
       //jtpTrabajo.setIconAt(jtpTrabajo.getTabCount()-1, new javax.swing.ImageIcon(getClass().getResource("/Images/error.png")));
       PanelTab btc=new PanelTab(jtpTrabajo,1);
       jtpTrabajo.setTabComponentAt(jtpTrabajo.getTabCount()-1, btc);
       comprobantePago.focusTable();
    }
    private void modificarTipoCambio() {
        JTextField textField1 = new JTextField((COMPRA>0)?String.valueOf(COMPRA):"3.2");
        JTextField textField2 = new JTextField((VENTA>0)?String.valueOf(VENTA):"3.3");
        Object[] inputFields = {"Compra", textField1,
                                "Venta", textField2};
        int option = JOptionPane.showConfirmDialog(this, inputFields, "Tipo de cambio", JOptionPane.OK_CANCEL_OPTION, JOptionPane.INFORMATION_MESSAGE,new javax.swing.ImageIcon(getClass().getResource("/Images/sunat_logo.png")));
        if(option == JOptionPane.OK_OPTION) {
            COMPRA=Float.parseFloat(textField1.getText());
            VENTA=Float.parseFloat(textField2.getText());
        }
        asginarTipoCambio();
    }

    private void datosEmpresa() {
        PreparedStatement stmt;
        jlNombreEmpresa.setText(empresa.getNombreComercial());
        try {
            stmt = conn.prepareStatement("SELECT * from Cuenta where idCuenta=?");
            stmt.setInt(1, idCuenta);
            ResultSet rs=stmt.executeQuery();
            cuenta=new Cuenta();
            while(rs.next()){
                cuenta.setIdCuenta(rs.getInt("idCuenta"));
                cuenta.setUsuario(rs.getString("usuario"));
                cuenta.setNombrePersona(rs.getString("nombrePersona"));
                cuenta.setEmpresaIdEmpresa(rs.getInt("Empresa_idEmpresa"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(MainView.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        jlUsuario.setText(cuenta.getNombrePersona());
    }

    private void asginarTipoCambio() {
        jlCompraSunat.setText(String.valueOf(COMPRA));
        jlVentaSunat.setText(String.valueOf(VENTA));
    }

    private void nuevaBoleta() {
        Comprobante comprobantePago=new Comprobante(this.jtpTrabajo,this.empresa,"B", COMPRA, VENTA,idCuenta);
        jtpTrabajo.addTab("Boleta",comprobantePago);
        jtpTrabajo.setSelectedIndex(jtpTrabajo.getTabCount()-1);
        comprobantePago.jlTipoDocumento.setText("DNI:");
        //comprobantePago.jsDescuento.setEnabled(false);
        PanelTab btc=new PanelTab(jtpTrabajo,1);
        jtpTrabajo.setTabComponentAt(jtpTrabajo.getTabCount()-1, btc);
        comprobantePago.focusTable();
    }

    private void eventosTeclado() {
        KeyStroke copy=KeyStroke.getKeyStroke(com.sun.glass.events.KeyEvent.VK_C, Event.CTRL_MASK);
        Action performCopy = new AbstractAction("copy") { 
            public void actionPerformed(ActionEvent e) {     
                copiarPortapapeles();
            }
        };
        KeyStroke keyF1=KeyStroke.getKeyStroke(com.sun.glass.events.KeyEvent.VK_F1, 0,true);
        Action performFactura = new AbstractAction("Factura") { 
            public void actionPerformed(ActionEvent e) {     
                nuevaFactura();
            }
        };
        jbFactura.getActionMap().put("Factura", performFactura);
        jbFactura.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(keyF1, "Factura");
        KeyStroke keyF2=KeyStroke.getKeyStroke(com.sun.glass.events.KeyEvent.VK_F2, 0,true);
        Action performBoleta = new AbstractAction("Boleta") { 
            public void actionPerformed(ActionEvent e) {     
                nuevaBoleta();
            }
        };
        jbBoleta.getActionMap().put("Boleta", performFactura);
        jbBoleta.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(keyF2, "Boleta");
        KeyStroke keyF3=KeyStroke.getKeyStroke(com.sun.glass.events.KeyEvent.VK_F3, 0,true);
        Action performNCredito = new AbstractAction("NCredito") { 
            public void actionPerformed(ActionEvent e) {     
                nuevaNotaCredito();
            }
        };
        jbNotaCredito.getActionMap().put("NCredito", performNCredito);
        jbNotaCredito.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(keyF3, "NCredito");
        KeyStroke keyF4=KeyStroke.getKeyStroke(com.sun.glass.events.KeyEvent.VK_F4, 0,true);
        Action performNDebito = new AbstractAction("NDebito") { 
            public void actionPerformed(ActionEvent e) {     
                nuevaNotaDebito();
            }
        };
        jbNotaDebito.getActionMap().put("NDebito", performNDebito);
        jbNotaDebito.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(keyF4, "NDebito");
        
    }
    private void copiarPortapapeles(){
        
    }

    private void agregarTipoCambio() {
        PreparedStatement stmt;
        try {
            stmt = conn.prepareStatement("select * from tipocambiosunat where idTipocambio=curdate()");
            ResultSet rs=stmt.executeQuery();
            if(rs.next()){
                COMPRA=rs.getFloat("compra");
                VENTA=rs.getFloat("venta");
            }
            else{
                if(!tipoCambioSunat()){
                    COMPRA=3.237f;
                    VENTA=3.24f;
                }
                insertTipoCambio();
            }
            asginarTipoCambio();
        } catch (SQLException ex) {
            Logger.getLogger(MainView.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    private void insertTipoCambio() throws SQLException{
        tipoCambioSunat();
        PreparedStatement stmt;
        stmt = conn.prepareStatement("insert into tipocambiosunat (compra,`venta`) values(?,?)");
        stmt.setFloat(1, COMPRA);
        stmt.setFloat(2, VENTA);
        stmt.executeUpdate();
    }

    private void nuevaNotaCredito() {
        Comprobante comprobantePago=new Comprobante(this.jtpTrabajo,this.empresa,"C", COMPRA, VENTA,idCuenta);
        jtpTrabajo.addTab("Nota de Crédito",comprobantePago);
        jtpTrabajo.setSelectedIndex(jtpTrabajo.getTabCount()-1);
        comprobantePago.jlTipoDocumento.setText("Cliente:");
        comprobantePago.jsDescuento.setEnabled(false);
        comprobantePago.jcbMotivo.setVisible(true);
        comprobantePago.jrbDocReferencia.setText("Doc Referencia");
        comprobantePago.jrbDocReferencia.setSelected(true);
        comprobantePago.jrbDocReferencia.setEnabled(false);
        for(int i=0;i<tipoNotaCredito.length;i++){
            comprobantePago.jcbMotivo.addItem(tipoNotaCredito[i]);
        }
        PanelTab btc=new PanelTab(jtpTrabajo,1);
        jtpTrabajo.setTabComponentAt(jtpTrabajo.getTabCount()-1, btc);
        comprobantePago.focusTable();
    }

    private void nuevaNotaDebito() {
         Comprobante comprobantePago=new Comprobante(this.jtpTrabajo,this.empresa,"D", COMPRA, VENTA,idCuenta);
        jtpTrabajo.addTab("Nota de Débito",comprobantePago);
        jtpTrabajo.setSelectedIndex(jtpTrabajo.getTabCount()-1);
        comprobantePago.jlTipoDocumento.setText("Cliente:");
        comprobantePago.jsDescuento.setEnabled(false);
        comprobantePago.jcbMotivo.setVisible(true);
        comprobantePago.jrbDocReferencia.setText("Doc Referencia");
        comprobantePago.jrbDocReferencia.setSelected(true);
        comprobantePago.jrbDocReferencia.setEnabled(false);
        for(int i=0;i<tipoNotaDébito.length;i++){
            comprobantePago.jcbMotivo.addItem(tipoNotaDébito[i]);
        }
        PanelTab btc=new PanelTab(jtpTrabajo,1);
        jtpTrabajo.setTabComponentAt(jtpTrabajo.getTabCount()-1, btc);
        comprobantePago.focusTable();
    }

    private void iniciarTabInicio() {
        Image image = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Images/logoKipu.png"));
        BufferedImage originalImage =((ToolkitImage) image).getBufferedImage();
        int type = originalImage.getType() == 0? BufferedImage.TYPE_INT_ARGB : originalImage.getType();
        jlLogo.setIcon(new ImageIcon(this.resizeImage(originalImage, type)));
    }
    private  BufferedImage resizeImage(BufferedImage originalImage, int type){
		int IMG_WIDTH = 500;//jlLogo.getWidth();
                int IMG_HEIGHT =500;//jlLogo.getHeight();
                BufferedImage resizedImage = new BufferedImage(IMG_WIDTH, IMG_HEIGHT, type);
		Graphics2D g = resizedImage.createGraphics();
		g.drawImage(originalImage, 0, 0, IMG_WIDTH, IMG_HEIGHT, null);
		g.dispose();
		return resizedImage;
    }

}
