/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import Controllers.ConnectionDB;
import Models.Empresa;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


/**
 *
 * @author javierfuenteshuertas
 */
public class Usuario extends javax.swing.JFrame {

    /**
     * Creates new form Usuario
     */
    private ConnectionDB conexion;
    private Connection conn;
    private Empresa empresa;
    public Usuario(Empresa empresa) {
        initComponents();
        this.empresa=empresa;
        conexion=new ConnectionDB();
        conn=conexion.connect(conn);
        inciarEventosTeclado();
        this.getRootPane().setDefaultButton(jbAgregarUsuario);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jtPassword = new javax.swing.JPasswordField();
        jtUsuario = new javax.swing.JTextField();
        jtRepetir = new javax.swing.JPasswordField();
        jtNombres = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jbAgregarUsuario = new javax.swing.JButton();

        setTitle("Nuevo Usuario");

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));

        jtPassword.setText("12345");
        jtPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtPasswordKeyPressed(evt);
            }
        });

        jtUsuario.setForeground(new java.awt.Color(153, 153, 153));
        jtUsuario.setText("Nombre de usuario");
        jtUsuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtUsuarioFocusLost(evt);
            }
        });
        jtUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtUsuarioMouseClicked(evt);
            }
        });
        jtUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtUsuarioKeyPressed(evt);
            }
        });

        jtRepetir.setText("12345");
        jtRepetir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtRepetirKeyPressed(evt);
            }
        });

        jtNombres.setForeground(new java.awt.Color(153, 153, 153));
        jtNombres.setText("Nombre del trabajador");
        jtNombres.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtNombresFocusLost(evt);
            }
        });
        jtNombres.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtNombresMouseClicked(evt);
            }
        });
        jtNombres.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtNombresKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtRepetir)
                    .addComponent(jtNombres, javax.swing.GroupLayout.DEFAULT_SIZE, 321, Short.MAX_VALUE)
                    .addComponent(jtUsuario, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jtPassword))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jtNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtRepetir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/error.png"))); // NOI18N
        jButton1.setText("Cancelar");
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setPreferredSize(new java.awt.Dimension(58, 62));
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jbAgregarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/success.png"))); // NOI18N
        jbAgregarUsuario.setText("Agregar");
        jbAgregarUsuario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbAgregarUsuario.setMaximumSize(new java.awt.Dimension(58, 62));
        jbAgregarUsuario.setSelected(true);
        jbAgregarUsuario.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbAgregarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAgregarUsuarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbAgregarUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbAgregarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6))
        );

        jbAgregarUsuario.setDefaultCapable(true);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jbAgregarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAgregarUsuarioActionPerformed
        agregarUsuario();
    }//GEN-LAST:event_jbAgregarUsuarioActionPerformed

    private void jtNombresFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtNombresFocusLost
        if(jtNombres.getText().length()==0){
            jtNombres.setText("Nombre del trabajador");
            jtNombres.setForeground(new java.awt.Color(153, 153, 153));
        }
    }//GEN-LAST:event_jtNombresFocusLost

    private void jtNombresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtNombresMouseClicked
        if(jtNombres.getText().equals("Nombre del trabajador")){
            jtNombres.setText("");
            jtNombres.setForeground(new java.awt.Color(0, 0, 0));
        }
        else{
            jtNombres.setForeground(new java.awt.Color(0, 0, 0));
        }
        
    }//GEN-LAST:event_jtNombresMouseClicked

    private void jtNombresKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtNombresKeyPressed
        if(jtNombres.getText().equals("Nombre del trabajador")){
            jtNombres.setText("");
            jtNombres.setForeground(new java.awt.Color(0, 0, 0));
        }
    }//GEN-LAST:event_jtNombresKeyPressed

    private void jtUsuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtUsuarioKeyPressed
        if(jtUsuario.getText().equals("Nombre de usuario")){
            jtUsuario.setText("");
            jtUsuario.setForeground(new java.awt.Color(0, 0, 0));
        }
    }//GEN-LAST:event_jtUsuarioKeyPressed

    private void jtUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtUsuarioMouseClicked
        if(jtUsuario.getText().equals("Nombre de usuario")){
            jtUsuario.setText("");
            jtUsuario.setForeground(new java.awt.Color(0, 0, 0));
        }
        else{
            jtUsuario.setForeground(new java.awt.Color(0, 0, 0));
        }
    }//GEN-LAST:event_jtUsuarioMouseClicked

    private void jtUsuarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtUsuarioFocusLost
        if(jtUsuario.getText().length()==0){
            jtUsuario.setText("Nombre de usuario");
            jtUsuario.setForeground(new java.awt.Color(153, 153, 153));
        }
    }//GEN-LAST:event_jtUsuarioFocusLost

    private void jtPasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtPasswordKeyPressed
        jtPassword.setText("");
    }//GEN-LAST:event_jtPasswordKeyPressed

    private void jtRepetirKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtRepetirKeyPressed
        jtRepetir.setText("");
    }//GEN-LAST:event_jtRepetirKeyPressed
    private void agregarUsuario(){
        if(jtUsuario.getText().length()<=0){
            JOptionPane.showMessageDialog(null,"Debe ingresar un usuario");
            return;
        }
        if(validarContrasenias()){
            guardarUsuario();
            JOptionPane.showMessageDialog(null,"Se agregó correctamente");
            this.setVisible(false);
        }
    }
    /**
     * @param args the command line arguments
     */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbAgregarUsuario;
    private javax.swing.JTextField jtNombres;
    private javax.swing.JPasswordField jtPassword;
    private javax.swing.JPasswordField jtRepetir;
    private javax.swing.JTextField jtUsuario;
    // End of variables declaration//GEN-END:variables

    private Boolean validarContrasenias() {
        String password=String.valueOf(jtPassword.getPassword());
        String repetir=String.valueOf(jtRepetir.getPassword());
        if(password.equals(repetir))return true;
        else {
            JOptionPane.showMessageDialog(null, "Los password  no coinciden");
            return false;
        }
    }

    private void guardarUsuario() {
        PreparedStatement stmt;
        try {
            stmt = conn.prepareStatement("call createAccount(?,?,?,?)");
            stmt.setString(1, jtUsuario.getText());
            String pass=String.valueOf(jtPassword.getPassword());
            stmt.setString(2, pass);
            stmt.setString(3, jtNombres.getText());
            stmt.setInt(4, empresa.getIdEmpresa());
            stmt.executeUpdate();
        } catch (SQLException ex) {
            Logger.getLogger(Usuario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void inciarEventosTeclado() {
        //Agrega un  nuevo producto si se presiona la tecla '+' 
        getRootPane().getInputMap(javax.swing.JComponent.WHEN_IN_FOCUSED_WINDOW).put(
            javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0), "Cancel");
        
        getRootPane().getActionMap().put("Cancel", new javax.swing.AbstractAction(){
            @Override
            public void actionPerformed(java.awt.event.ActionEvent e)
            {
               setVisible(false);
            }
        });
        getRootPane().getInputMap(javax.swing.JComponent.WHEN_IN_FOCUSED_WINDOW).put(
            javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ENTER, 0), "Add");
        
        getRootPane().getActionMap().put("Add", new javax.swing.AbstractAction(){
            @Override
            public void actionPerformed(java.awt.event.ActionEvent e)
            {
               agregarUsuario();
            }
        });
    }
}
