package Models;
// Generated 09-sep-2017 12:20:57 by Hibernate Tools 4.3.1



/**
 * Cliente generated by hbm2java
 */
public class Cliente extends ClienteId implements java.io.Serializable {


     private ClienteId id;
     private String direccion;
     private String email;
     private String nombre;
     private String ubigeo;

    public Cliente() {
    }

	
    public Cliente(ClienteId id, String email, String nombre) {
        this.id = id;
        this.email = email;
        this.nombre = nombre;
    }
    public Cliente(ClienteId id, String direccion, String email, String nombre, String ubigeo) {
       this.id = id;
       this.direccion = direccion;
       this.email = email;
       this.nombre = nombre;
       this.ubigeo = ubigeo;
    }
   
    public ClienteId getId() {
        return this.id;
    }
    
    public void setId(ClienteId id) {
        this.id = id;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getUbigeo() {
        return this.ubigeo;
    }
    
    public void setUbigeo(String ubigeo) {
        this.ubigeo = ubigeo;
    }




}


