package Models;
// Generated 09-sep-2017 12:20:57 by Hibernate Tools 4.3.1



/**
 * ClienteId generated by hbm2java
 */
public class ClienteId  implements java.io.Serializable {


     private String numero;
     private String tipoDocumento;

    public ClienteId() {
    }

    public ClienteId(String numero, String tipoDocumento) {
       this.numero = numero;
       this.tipoDocumento = tipoDocumento;
    }
   
    public String getNumero() {
        return this.numero;
    }
    
    public void setNumero(String numero) {
        this.numero = numero;
    }
    public String getTipoDocumento() {
        return this.tipoDocumento;
    }
    
    public void setTipoDocumento(String tipoDocumento) {
        this.tipoDocumento = tipoDocumento;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ClienteId) ) return false;
		 ClienteId castOther = ( ClienteId ) other; 
         
		 return ( (this.getNumero()==castOther.getNumero()) || ( this.getNumero()!=null && castOther.getNumero()!=null && this.getNumero().equals(castOther.getNumero()) ) )
 && ( (this.getTipoDocumento()==castOther.getTipoDocumento()) || ( this.getTipoDocumento()!=null && castOther.getTipoDocumento()!=null && this.getTipoDocumento().equals(castOther.getTipoDocumento()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getNumero() == null ? 0 : this.getNumero().hashCode() );
         result = 37 * result + ( getTipoDocumento() == null ? 0 : this.getTipoDocumento().hashCode() );
         return result;
   }   


}


