package Models;
// Generated 09-sep-2017 12:20:57 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * ComprobantePago generated by hbm2java
 */
public class ComprobantePago extends ComprobantePagoId implements java.io.Serializable {


     private ComprobantePagoId id;
     private float saldoBruto;
     private float impuesto;
     private float total;
     private String moneda;
     private Date fechaEmision;
     private String observacion;
     private String estado;
     private Date fechaRegistro;
     private String clienteNumero;
     private int cuentaIdCuenta;
     private String serieGuia;
     private String numGuia;
     private Integer descuentoGlobal;
     private Integer motivo;

    public ComprobantePago() {
    }

	
    public ComprobantePago(ComprobantePagoId id, float saldoBruto, float impuesto, float total, String moneda, Date fechaEmision, String estado, String clienteNumero, int cuentaIdCuenta) {
        this.id = id;
        this.saldoBruto = saldoBruto;
        this.impuesto = impuesto;
        this.total = total;
        this.moneda = moneda;
        this.fechaEmision = fechaEmision;
        this.estado = estado;
        this.clienteNumero = clienteNumero;
        this.cuentaIdCuenta = cuentaIdCuenta;
    }
    public ComprobantePago(ComprobantePagoId id, float saldoBruto, float impuesto, float total, String moneda, Date fechaEmision, String observacion, String estado, Date fechaRegistro, String clienteNumero, int cuentaIdCuenta, String serieGuia, String numGuia, Integer descuentoGlobal, Integer motivo) {
       this.id = id;
       this.saldoBruto = saldoBruto;
       this.impuesto = impuesto;
       this.total = total;
       this.moneda = moneda;
       this.fechaEmision = fechaEmision;
       this.observacion = observacion;
       this.estado = estado;
       this.fechaRegistro = fechaRegistro;
       this.clienteNumero = clienteNumero;
       this.cuentaIdCuenta = cuentaIdCuenta;
       this.serieGuia = serieGuia;
       this.numGuia = numGuia;
       this.descuentoGlobal = descuentoGlobal;
       this.motivo = motivo;
    }
   
    public ComprobantePagoId getId() {
        return this.id;
    }
    
    public void setId(ComprobantePagoId id) {
        this.id = id;
    }
    public float getSaldoBruto() {
        return this.saldoBruto;
    }
    
    public void setSaldoBruto(float saldoBruto) {
        this.saldoBruto = saldoBruto;
    }
    public float getImpuesto() {
        return this.impuesto;
    }
    
    public void setImpuesto(float impuesto) {
        this.impuesto = impuesto;
    }
    public float getTotal() {
        return this.total;
    }
    
    public void setTotal(float total) {
        this.total = total;
    }
    public String getMoneda() {
        return this.moneda;
    }
    
    public void setMoneda(String moneda) {
        this.moneda = moneda;
    }
    public Date getFechaEmision() {
        return this.fechaEmision;
    }
    
    public void setFechaEmision(Date fechaEmision) {
        this.fechaEmision = fechaEmision;
    }
    public String getObservacion() {
        return this.observacion;
    }
    
    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }
    
    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }
    public String getClienteNumero() {
        return this.clienteNumero;
    }
    
    public void setClienteNumero(String clienteNumero) {
        this.clienteNumero = clienteNumero;
    }
    public int getCuentaIdCuenta() {
        return this.cuentaIdCuenta;
    }
    
    public void setCuentaIdCuenta(int cuentaIdCuenta) {
        this.cuentaIdCuenta = cuentaIdCuenta;
    }
    public String getSerieGuia() {
        return this.serieGuia;
    }
    
    public void setSerieGuia(String serieGuia) {
        this.serieGuia = serieGuia;
    }
    public String getNumGuia() {
        return this.numGuia;
    }
    
    public void setNumGuia(String numGuia) {
        this.numGuia = numGuia;
    }
    public Integer getDescuentoGlobal() {
        return this.descuentoGlobal;
    }
    
    public void setDescuentoGlobal(Integer descuentoGlobal) {
        this.descuentoGlobal = descuentoGlobal;
    }
    public Integer getMotivo() {
        return this.motivo;
    }
    
    public void setMotivo(Integer motivo) {
        this.motivo = motivo;
    }




}


