package Models;
// Generated 09-sep-2017 12:20:57 by Hibernate Tools 4.3.1



/**
 * CorreoEmpresa generated by hbm2java
 */
public class CorreoEmpresa  implements java.io.Serializable {


     private String email;
     private byte[] passwordEmail;
     private int empresaIdEmpresa;
     private String starttls;
     private String host;
     private String port;

    public CorreoEmpresa() {
    }

	
    public CorreoEmpresa(String email, byte[] passwordEmail, int empresaIdEmpresa, String starttls) {
        this.email = email;
        this.passwordEmail = passwordEmail;
        this.empresaIdEmpresa = empresaIdEmpresa;
        this.starttls = starttls;
    }
    public CorreoEmpresa(String email, byte[] passwordEmail, int empresaIdEmpresa, String starttls, String host, String port) {
       this.email = email;
       this.passwordEmail = passwordEmail;
       this.empresaIdEmpresa = empresaIdEmpresa;
       this.starttls = starttls;
       this.host = host;
       this.port = port;
    }
   
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public byte[] getPasswordEmail() {
        return this.passwordEmail;
    }
    
    public void setPasswordEmail(byte[] passwordEmail) {
        this.passwordEmail = passwordEmail;
    }
    public int getEmpresaIdEmpresa() {
        return this.empresaIdEmpresa;
    }
    
    public void setEmpresaIdEmpresa(int empresaIdEmpresa) {
        this.empresaIdEmpresa = empresaIdEmpresa;
    }
    public String getStarttls() {
        return this.starttls;
    }
    
    public void setStarttls(String starttls) {
        this.starttls = starttls;
    }
    public String getHost() {
        return this.host;
    }
    
    public void setHost(String host) {
        this.host = host;
    }
    public String getPort() {
        return this.port;
    }
    
    public void setPort(String port) {
        this.port = port;
    }




}


