package Models;
// Generated 09-sep-2017 12:20:57 by Hibernate Tools 4.3.1



/**
 * CuentaId generated by hbm2java
 */
public class CuentaId  implements java.io.Serializable {


     private int idCuenta;
     private int empresaIdEmpresa;

    public CuentaId() {
    }

    public CuentaId(int idCuenta, int empresaIdEmpresa) {
       this.idCuenta = idCuenta;
       this.empresaIdEmpresa = empresaIdEmpresa;
    }
   
    public int getIdCuenta() {
        return this.idCuenta;
    }
    
    public void setIdCuenta(int idCuenta) {
        this.idCuenta = idCuenta;
    }
    public int getEmpresaIdEmpresa() {
        return this.empresaIdEmpresa;
    }
    
    public void setEmpresaIdEmpresa(int empresaIdEmpresa) {
        this.empresaIdEmpresa = empresaIdEmpresa;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CuentaId) ) return false;
		 CuentaId castOther = ( CuentaId ) other; 
         
		 return (this.getIdCuenta()==castOther.getIdCuenta())
 && (this.getEmpresaIdEmpresa()==castOther.getEmpresaIdEmpresa());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdCuenta();
         result = 37 * result + this.getEmpresaIdEmpresa();
         return result;
   }   


}


