package Models;
// Generated 09-sep-2017 12:20:57 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Cuenta generated by hbm2java
 */
public class Cuenta  extends CuentaId implements java.io.Serializable {


     private CuentaId id;
     private String usuario;
     private byte[] password;
     private Date ultimoAcceso;
     private String nombrePersona;

    public Cuenta() {
    }

	
    public Cuenta(CuentaId id, String usuario, byte[] password) {
        this.id = id;
        this.usuario = usuario;
        this.password = password;
    }
    public Cuenta(CuentaId id, String usuario, byte[] password, Date ultimoAcceso, String nombrePersona) {
       this.id = id;
       this.usuario = usuario;
       this.password = password;
       this.ultimoAcceso = ultimoAcceso;
       this.nombrePersona = nombrePersona;
    }
   
    public CuentaId getId() {
        return this.id;
    }
    
    public void setId(CuentaId id) {
        this.id = id;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public byte[] getPassword() {
        return this.password;
    }
    
    public void setPassword(byte[] password) {
        this.password = password;
    }
    public Date getUltimoAcceso() {
        return this.ultimoAcceso;
    }
    
    public void setUltimoAcceso(Date ultimoAcceso) {
        this.ultimoAcceso = ultimoAcceso;
    }
    public String getNombrePersona() {
        return this.nombrePersona;
    }
    
    public void setNombrePersona(String nombrePersona) {
        this.nombrePersona = nombrePersona;
    }




}


