package Models;
// Generated 09-sep-2017 12:20:57 by Hibernate Tools 4.3.1



/**
 * EmpresaHasProducto generated by hbm2java
 */
public class EmpresaHasProducto extends EmpresaHasProductoId implements java.io.Serializable {


     private EmpresaHasProductoId id;
     private float precioUnit;
     private String unidadMedida;
     private String moneda;

    public EmpresaHasProducto() {
    }

    public EmpresaHasProducto(EmpresaHasProductoId id, float precioUnit, String unidadMedida, String moneda) {
       this.id = id;
       this.precioUnit = precioUnit;
       this.unidadMedida = unidadMedida;
       this.moneda = moneda;
    }
   
    public EmpresaHasProductoId getId() {
        return this.id;
    }
    
    public void setId(EmpresaHasProductoId id) {
        this.id = id;
    }
    public float getPrecioUnit() {
        return this.precioUnit;
    }
    
    public void setPrecioUnit(float precioUnit) {
        this.precioUnit = precioUnit;
    }
    public String getUnidadMedida() {
        return this.unidadMedida;
    }
    
    public void setUnidadMedida(String unidadMedida) {
        this.unidadMedida = unidadMedida;
    }
    public String getMoneda() {
        return this.moneda;
    }
    
    public void setMoneda(String moneda) {
        this.moneda = moneda;
    }




}


