package Models;
// Generated 09-sep-2017 12:20:57 by Hibernate Tools 4.3.1



/**
 * EmpresaHasProductoId generated by hbm2java
 */
public class EmpresaHasProductoId  implements java.io.Serializable {


     private int empresaIdEmpresa;
     private String productoIdProducto;

    public EmpresaHasProductoId() {
    }

    public EmpresaHasProductoId(int empresaIdEmpresa, String productoIdProducto) {
       this.empresaIdEmpresa = empresaIdEmpresa;
       this.productoIdProducto = productoIdProducto;
    }
   
    public int getEmpresaIdEmpresa() {
        return this.empresaIdEmpresa;
    }
    
    public void setEmpresaIdEmpresa(int empresaIdEmpresa) {
        this.empresaIdEmpresa = empresaIdEmpresa;
    }
    public String getProductoIdProducto() {
        return this.productoIdProducto;
    }
    
    public void setProductoIdProducto(String productoIdProducto) {
        this.productoIdProducto = productoIdProducto;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof EmpresaHasProductoId) ) return false;
		 EmpresaHasProductoId castOther = ( EmpresaHasProductoId ) other; 
         
		 return (this.getEmpresaIdEmpresa()==castOther.getEmpresaIdEmpresa())
 && ( (this.getProductoIdProducto()==castOther.getProductoIdProducto()) || ( this.getProductoIdProducto()!=null && castOther.getProductoIdProducto()!=null && this.getProductoIdProducto().equals(castOther.getProductoIdProducto()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getEmpresaIdEmpresa();
         result = 37 * result + ( getProductoIdProducto() == null ? 0 : this.getProductoIdProducto().hashCode() );
         return result;
   }   


}


