package Models;
// Generated 09-sep-2017 12:20:57 by Hibernate Tools 4.3.1



/**
 * OrdenadorHasEmpresa generated by hbm2java
 */
public class OrdenadorHasEmpresa  implements java.io.Serializable {


     private OrdenadorHasEmpresaId id;

    public OrdenadorHasEmpresa() {
    }

    public OrdenadorHasEmpresa(OrdenadorHasEmpresaId id) {
       this.id = id;
    }
   
    public OrdenadorHasEmpresaId getId() {
        return this.id;
    }
    
    public void setId(OrdenadorHasEmpresaId id) {
        this.id = id;
    }




}


