package Models;
// Generated 09-sep-2017 12:20:57 by Hibernate Tools 4.3.1



/**
 * OrdenadorHasEmpresaId generated by hbm2java
 */
public class OrdenadorHasEmpresaId  implements java.io.Serializable {


     private int ordenadorIdOrdenador;
     private int empresaIdEmpresa;

    public OrdenadorHasEmpresaId() {
    }

    public OrdenadorHasEmpresaId(int ordenadorIdOrdenador, int empresaIdEmpresa) {
       this.ordenadorIdOrdenador = ordenadorIdOrdenador;
       this.empresaIdEmpresa = empresaIdEmpresa;
    }
   
    public int getOrdenadorIdOrdenador() {
        return this.ordenadorIdOrdenador;
    }
    
    public void setOrdenadorIdOrdenador(int ordenadorIdOrdenador) {
        this.ordenadorIdOrdenador = ordenadorIdOrdenador;
    }
    public int getEmpresaIdEmpresa() {
        return this.empresaIdEmpresa;
    }
    
    public void setEmpresaIdEmpresa(int empresaIdEmpresa) {
        this.empresaIdEmpresa = empresaIdEmpresa;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof OrdenadorHasEmpresaId) ) return false;
		 OrdenadorHasEmpresaId castOther = ( OrdenadorHasEmpresaId ) other; 
         
		 return (this.getOrdenadorIdOrdenador()==castOther.getOrdenadorIdOrdenador())
 && (this.getEmpresaIdEmpresa()==castOther.getEmpresaIdEmpresa());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getOrdenadorIdOrdenador();
         result = 37 * result + this.getEmpresaIdEmpresa();
         return result;
   }   


}


