package Models;
// Generated 09-sep-2017 12:20:57 by Hibernate Tools 4.3.1



/**
 * PermisoHasCuentaId generated by hbm2java
 */
public class PermisoHasCuentaId  implements java.io.Serializable {


     private int permisoIdPermiso;
     private int cuentaIdCuenta;

    public PermisoHasCuentaId() {
    }

    public PermisoHasCuentaId(int permisoIdPermiso, int cuentaIdCuenta) {
       this.permisoIdPermiso = permisoIdPermiso;
       this.cuentaIdCuenta = cuentaIdCuenta;
    }
   
    public int getPermisoIdPermiso() {
        return this.permisoIdPermiso;
    }
    
    public void setPermisoIdPermiso(int permisoIdPermiso) {
        this.permisoIdPermiso = permisoIdPermiso;
    }
    public int getCuentaIdCuenta() {
        return this.cuentaIdCuenta;
    }
    
    public void setCuentaIdCuenta(int cuentaIdCuenta) {
        this.cuentaIdCuenta = cuentaIdCuenta;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PermisoHasCuentaId) ) return false;
		 PermisoHasCuentaId castOther = ( PermisoHasCuentaId ) other; 
         
		 return (this.getPermisoIdPermiso()==castOther.getPermisoIdPermiso())
 && (this.getCuentaIdCuenta()==castOther.getCuentaIdCuenta());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getPermisoIdPermiso();
         result = 37 * result + this.getCuentaIdCuenta();
         return result;
   }   


}


