package Models;
// Generated 09-sep-2017 12:20:57 by Hibernate Tools 4.3.1



/**
 * Producto generated by hbm2java
 */
public class Producto extends EmpresaHasProducto implements java.io.Serializable {


     private String idProducto;
     private String descripcion;
     private float cantidad;
     private float impuesto;
    public Producto() {
    }

    public Producto(String idProducto, String descripcion) {
       this.idProducto = idProducto;
       this.descripcion = descripcion;
    }
   
    public String getIdProducto() {
        return this.idProducto;
    }
    
    public void setIdProducto(String idProducto) {
        this.idProducto = idProducto;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    public float getCantidad() {
        return cantidad;
    }

    public void setCantidad(float cantidad) {
        this.cantidad = cantidad;
    }

    public float getImpuesto() {
        return impuesto;
    }

    public void setImpuesto(float impuesto) {
        this.impuesto = impuesto;
    }
    



}


