package Models;
// Generated 09-sep-2017 12:20:57 by Hibernate Tools 4.3.1



/**
 * ProductoHasComprobantePagoId generated by hbm2java
 */
public class ProductoHasComprobantePagoId  implements java.io.Serializable {


     private String productoIdProducto;
     private String comprobantePagoSerieComprobante;
     private int comprobantePagoEmpresaIdEmpresa;
     private String comprobantePagoTipoComprobanteIdTipoComprobante;

    public ProductoHasComprobantePagoId() {
    }

    public ProductoHasComprobantePagoId(String productoIdProducto, String comprobantePagoSerieComprobante, int comprobantePagoEmpresaIdEmpresa, String comprobantePagoTipoComprobanteIdTipoComprobante) {
       this.productoIdProducto = productoIdProducto;
       this.comprobantePagoSerieComprobante = comprobantePagoSerieComprobante;
       this.comprobantePagoEmpresaIdEmpresa = comprobantePagoEmpresaIdEmpresa;
       this.comprobantePagoTipoComprobanteIdTipoComprobante = comprobantePagoTipoComprobanteIdTipoComprobante;
    }
   
    public String getProductoIdProducto() {
        return this.productoIdProducto;
    }
    
    public void setProductoIdProducto(String productoIdProducto) {
        this.productoIdProducto = productoIdProducto;
    }
    public String getComprobantePagoSerieComprobante() {
        return this.comprobantePagoSerieComprobante;
    }
    
    public void setComprobantePagoSerieComprobante(String comprobantePagoSerieComprobante) {
        this.comprobantePagoSerieComprobante = comprobantePagoSerieComprobante;
    }
    public int getComprobantePagoEmpresaIdEmpresa() {
        return this.comprobantePagoEmpresaIdEmpresa;
    }
    
    public void setComprobantePagoEmpresaIdEmpresa(int comprobantePagoEmpresaIdEmpresa) {
        this.comprobantePagoEmpresaIdEmpresa = comprobantePagoEmpresaIdEmpresa;
    }
    public String getComprobantePagoTipoComprobanteIdTipoComprobante() {
        return this.comprobantePagoTipoComprobanteIdTipoComprobante;
    }
    
    public void setComprobantePagoTipoComprobanteIdTipoComprobante(String comprobantePagoTipoComprobanteIdTipoComprobante) {
        this.comprobantePagoTipoComprobanteIdTipoComprobante = comprobantePagoTipoComprobanteIdTipoComprobante;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ProductoHasComprobantePagoId) ) return false;
		 ProductoHasComprobantePagoId castOther = ( ProductoHasComprobantePagoId ) other; 
         
		 return ( (this.getProductoIdProducto()==castOther.getProductoIdProducto()) || ( this.getProductoIdProducto()!=null && castOther.getProductoIdProducto()!=null && this.getProductoIdProducto().equals(castOther.getProductoIdProducto()) ) )
 && ( (this.getComprobantePagoSerieComprobante()==castOther.getComprobantePagoSerieComprobante()) || ( this.getComprobantePagoSerieComprobante()!=null && castOther.getComprobantePagoSerieComprobante()!=null && this.getComprobantePagoSerieComprobante().equals(castOther.getComprobantePagoSerieComprobante()) ) )
 && (this.getComprobantePagoEmpresaIdEmpresa()==castOther.getComprobantePagoEmpresaIdEmpresa())
 && ( (this.getComprobantePagoTipoComprobanteIdTipoComprobante()==castOther.getComprobantePagoTipoComprobanteIdTipoComprobante()) || ( this.getComprobantePagoTipoComprobanteIdTipoComprobante()!=null && castOther.getComprobantePagoTipoComprobanteIdTipoComprobante()!=null && this.getComprobantePagoTipoComprobanteIdTipoComprobante().equals(castOther.getComprobantePagoTipoComprobanteIdTipoComprobante()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getProductoIdProducto() == null ? 0 : this.getProductoIdProducto().hashCode() );
         result = 37 * result + ( getComprobantePagoSerieComprobante() == null ? 0 : this.getComprobantePagoSerieComprobante().hashCode() );
         result = 37 * result + this.getComprobantePagoEmpresaIdEmpresa();
         result = 37 * result + ( getComprobantePagoTipoComprobanteIdTipoComprobante() == null ? 0 : this.getComprobantePagoTipoComprobanteIdTipoComprobante().hashCode() );
         return result;
   }   


}


