package Models;
// Generated 09-sep-2017 12:20:57 by Hibernate Tools 4.3.1



/**
 * ProductoHasComprobantePago generated by hbm2java
 */
public class ProductoHasComprobantePago  implements java.io.Serializable {


     private ProductoHasComprobantePagoId id;
     private float cantidad;
     private float impuesto;

    public ProductoHasComprobantePago() {
    }

    public ProductoHasComprobantePago(ProductoHasComprobantePagoId id, float cantidad, float impuesto) {
       this.id = id;
       this.cantidad = cantidad;
       this.impuesto = impuesto;
    }
   
    public ProductoHasComprobantePagoId getId() {
        return this.id;
    }
    
    public void setId(ProductoHasComprobantePagoId id) {
        this.id = id;
    }
    public float getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(float cantidad) {
        this.cantidad = cantidad;
    }
    public float getImpuesto() {
        return this.impuesto;
    }
    
    public void setImpuesto(float impuesto) {
        this.impuesto = impuesto;
    }




}


