package Models;
// Generated 09-sep-2017 12:20:57 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * TipoCambioSunat generated by hbm2java
 */
public class TipoCambioSunat  implements java.io.Serializable {


     private Date idTipoCambio;
     private float compra;
     private float venta;

    public TipoCambioSunat() {
    }

    public TipoCambioSunat(Date idTipoCambio, float compra, float venta) {
       this.idTipoCambio = idTipoCambio;
       this.compra = compra;
       this.venta = venta;
    }
   
    public Date getIdTipoCambio() {
        return this.idTipoCambio;
    }
    
    public void setIdTipoCambio(Date idTipoCambio) {
        this.idTipoCambio = idTipoCambio;
    }
    public float getCompra() {
        return this.compra;
    }
    
    public void setCompra(float compra) {
        this.compra = compra;
    }
    public float getVenta() {
        return this.venta;
    }
    
    public void setVenta(float venta) {
        this.venta = venta;
    }




}


